update to 1.1.1+17
AnacondaRecipes/ctypesgen-pypdfium2-team-feedstock pull request #2
Opened 2023-08-30 22:11 UTC by boldorider4

this commit belongs to the pypdfium2 branch and before Jul 4th (the date of release of pypdfium2 4.18.0) the last commit was 10b2b4be34c671613b3c4483bc068fa34e0a4d9e.

2023-08-30 22:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:24: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-08-30 22:20 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:24: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-08-31 10:22 UTC, M-Waszkiewicz-Anaconda approved these changes
LGTM

2023-08-31 11:34 UTC, skupr-anaconda approved these changes
LGTM but you can use `setuptools` and `setuptools-scm` without pinnings

2023-08-31 12:30 UTC, M-Waszkiewicz-Anaconda requested changes
can we test here if header exists ? looks like it do not for windows

2023-08-31 12:45 UTC, M-Waszkiewicz-Anaconda approved these changes

2023-08-31 12:45 UTC, M-Waszkiewicz-Anaconda commented
> can we test here if header exists ? looks like it do not for windows

actually I think it is dependency issue, so LGTM

2023-08-31 13:43 UTC, merged